### PR TITLE
Add Prettier, lint-staged and husky

### PR DESCRIPTION
**Pull request by ranmerc**
This PR adds Prettier to the project. I also took the liberty to add lint-staged and husky to ensure files are formatted before being committed. I have customized the .prettierrc configuration slightly, but let me know if you’d prefer a more opinionated setup.

### CODE REVIEW

**Comment by hussaino03** [comment]
@ranmerc Hey, thank you for this! Sorry, I should have clarified before. Can it be added to the server for now? We can add it later to the Client. It is just hard to review things combined in a single PR. I'd much prefer it if you did this in steps/stages so it is easier to trace any errors later. Thanks again.

**Comment by ranmerc** [comment]
Makes sense. Let me resolve conflicts and update it to be server only.

**Comment by ranmerc** [comment]
@hussaino03 You can check now.

**Review by hussaino03 — APPROVED** [review]
@ranmerc Looks good, you can start with the client now.

**Pull request merged**
